# TradeX Pro - Multilingual Support
# Supported Languages: English, Spanish, French, German, Italian, Portuguese, Russian, Chinese, Japanese, Arabic, Persian

LANGUAGES = {
    'en': {
        'code': 'en',
        'name': 'English',
        'flag': '🇺🇸',
        # Bot Messages
        'welcome_select_language': '🌍 **Welcome to TradeX Pro!**\n\nPlease select your preferred language:',
        'welcome_register': '🚀 **Welcome to TradeX Pro, {}!**\n\n🎁 **Special Gift:** Receive $10 FREE to start trading!\n\nClick "Register & Get $10" to claim your bonus and start your AI-powered trading journey!',
        'welcome_existing': '🚀 **Welcome back, {}!**\n\nYour account is ready for trading!\n\n💰 **Balance:** ${:.2f}\n📊 **Total Trades:** {}\n🏆 **Win Rate:** {:.1f}%',
        'register_success': '🎉 **Registration Successful!**\n\n💰 **$10 Gift Added!** Your starting balance is now $10,010\n\nReady to start AI-powered trading?',
        'trade_button': '🚀 Open TradeX Pro',
        'stats_button': '📊 My Stats',
        'deposit_button': '💰 Deposit',
        'withdraw_button': '💸 Withdraw', 
        'history_button': '📜 History',
        'help_button': '❓ Help',
        'language_button': '🌍 Language',
        
        # Mini App
        'app_title': 'TradeX Pro',
        'app_subtitle': 'AI-Powered Trading Bot',
        'balance_label': 'Your Balance',
        'ai_signal': 'AI Signal',
        'confidence': 'Confidence',
        'current_price': 'Current Price',
        'buy_button': 'BUY',
        'sell_button': 'SELL',
        'trade_amount_placeholder': 'Enter amount ($100-$1000)',
        'deposit_btn': 'Deposit',
        'withdraw_btn': 'Withdraw',
        'history_btn': 'History',
        'trade_in_progress': 'Trade in Progress',
        'entry_price': 'Entry',
        'current_price_label': 'Current',
        'profit_label': 'Profit',
        'congratulations': 'Congratulations! You won!',
        'better_luck': 'Better luck next time!',
        'trade_again': 'Trade Again',
        'transaction_history': 'Transaction History',
        'no_transactions': 'No transactions yet',
        'profit': 'Profit',
        'return': 'Return',
        'new_balance': 'New Balance'
    },
    
    'es': {
        'code': 'es',
        'name': 'Español', 
        'flag': '🇪🇸',
        'welcome_select_language': '🌍 **¡Bienvenido a TradeX Pro!**\n\nPor favor selecciona tu idioma preferido:',
        'welcome_register': '🚀 **¡Bienvenido a TradeX Pro, {}!**\n\n🎁 **Regalo Especial:** ¡Recibe $10 GRATIS para empezar a operar!\n\n¡Haz clic en "Registrarse y Obtener $10" para reclamar tu bono y comenzar tu viaje de trading con IA!',
        'welcome_existing': '🚀 **¡Bienvenido de vuelta, {}!**\n\n¡Tu cuenta está lista para operar!\n\n💰 **Saldo:** ${:.2f}\n📊 **Operaciones Totales:** {}\n🏆 **Tasa de Éxito:** {:.1f}%',
        'register_success': '🎉 **¡Registro Exitoso!**\n\n💰 **¡$10 de Regalo Añadidos!** Tu saldo inicial es ahora $10,010\n\n¿Listo para comenzar el trading con IA?',
        'trade_button': '🚀 Abrir TradeX Pro',
        'stats_button': '📊 Mis Estadísticas', 
        'deposit_button': '💰 Depositar',
        'withdraw_button': '💸 Retirar',
        'history_button': '📜 Historial',
        'help_button': '❓ Ayuda',
        'language_button': '🌍 Idioma',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'Bot de Trading con IA',
        'balance_label': 'Tu Saldo',
        'ai_signal': 'Señal IA',
        'confidence': 'Confianza',
        'current_price': 'Precio Actual',
        'buy_button': 'COMPRAR',
        'sell_button': 'VENDER',
        'trade_amount_placeholder': 'Ingresa cantidad ($100-$1000)',
        'deposit_btn': 'Depositar',
        'withdraw_btn': 'Retirar',
        'history_btn': 'Historial',
        'trade_in_progress': 'Operación en Progreso',
        'entry_price': 'Entrada',
        'current_price_label': 'Actual',
        'profit_label': 'Ganancia',
        'congratulations': '¡Felicidades! ¡Ganaste!',
        'better_luck': '¡Mejor suerte la próxima vez!',
        'trade_again': 'Operar Nuevamente',
        'transaction_history': 'Historial de Transacciones',
        'no_transactions': 'No hay transacciones aún',
        'profit': 'Ganancia',
        'return': 'Retorno',
        'new_balance': 'Nuevo Saldo'
    },
    
    'fr': {
        'code': 'fr',
        'name': 'Français',
        'flag': '🇫🇷',
        'welcome_select_language': '🌍 **Bienvenue sur TradeX Pro !**\n\nVeuillez sélectionner votre langue préférée :',
        'welcome_register': '🚀 **Bienvenue sur TradeX Pro, {} !**\n\n🎁 **Cadeau Spécial :** Recevez 10$ GRATUITS pour commencer à trader !\n\nCliquez sur "S\'inscrire et Obtenir 10$" pour réclamer votre bonus et commencer votre voyage de trading IA !',
        'welcome_existing': '🚀 **Bon retour, {} !**\n\nVotre compte est prêt pour le trading !\n\n💰 **Solde :** ${:.2f}\n📊 **Trades Totaux :** {}\n🏆 **Taux de Réussite :** {:.1f}%',
        'register_success': '🎉 **Inscription Réussie !**\n\n💰 **10$ de Cadeau Ajoutés !** Votre solde initial est maintenant de 10 010$\n\nPrêt à commencer le trading IA ?',
        'trade_button': '🚀 Ouvrir TradeX Pro',
        'stats_button': '📊 Mes Stats',
        'deposit_button': '💰 Dépôt',
        'withdraw_button': '💸 Retrait',
        'history_button': '📜 Historique',
        'help_button': '❓ Aide',
        'language_button': '🌍 Langue',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'Bot de Trading IA',
        'balance_label': 'Votre Solde',
        'ai_signal': 'Signal IA',
        'confidence': 'Confiance',
        'current_price': 'Prix Actuel',
        'buy_button': 'ACHETER',
        'sell_button': 'VENDRE',
        'trade_amount_placeholder': 'Entrez le montant ($100-$1000)',
        'deposit_btn': 'Dépôt',
        'withdraw_btn': 'Retrait',
        'history_btn': 'Historique',
        'trade_in_progress': 'Trade en Cours',
        'entry_price': 'Entrée',
        'current_price_label': 'Actuel',
        'profit_label': 'Profit',
        'congratulations': 'Félicitations ! Vous avez gagné !',
        'better_luck': 'Bonne chance la prochaine fois !',
        'trade_again': 'Trader à Nouveau',
        'transaction_history': 'Historique des Transactions',
        'no_transactions': 'Aucune transaction pour le moment',
        'profit': 'Profit',
        'return': 'Retour',
        'new_balance': 'Nouveau Solde'
    },
    
    'de': {
        'code': 'de',
        'name': 'Deutsch',
        'flag': '🇩🇪',
        'welcome_select_language': '🌍 **Willkommen bei TradeX Pro!**\n\nBitte wählen Sie Ihre bevorzugte Sprache:',
        'welcome_register': '🚀 **Willkommen bei TradeX Pro, {}!**\n\n🎁 **Spezialgeschenk:** Erhalten Sie $10 KOSTENLOS zum Handelsstart!\n\nKlicken Sie auf "Registrieren & $10 erhalten", um Ihren Bonus zu beanspruchen und Ihre KI-Trading-Reise zu beginnen!',
        'welcome_existing': '🚀 **Willkommen zurück, {}!**\n\nIhr Konto ist bereit zum Handeln!\n\n💰 **Guthaben:** ${:.2f}\n📊 **Gesamt Trades:** {}\n🏆 **Gewinnrate:** {:.1f}%',
        'register_success': '🎉 **Registrierung Erfolgreich!**\n\n💰 **$10 Geschenk Hinzugefügt!** Ihr Startguthaben beträgt jetzt $10,010\n\nBereit für KI-gestütztes Trading?',
        'trade_button': '🚀 TradeX Pro Öffnen',
        'stats_button': '📊 Meine Stats',
        'deposit_button': '💰 Einzahlung',
        'withdraw_button': '💸 Abhebung',
        'history_button': '📜 Historie',
        'help_button': '❓ Hilfe',
        'language_button': '🌍 Sprache',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'KI-Trading Bot',
        'balance_label': 'Ihr Guthaben',
        'ai_signal': 'KI-Signal',
        'confidence': 'Vertrauen',
        'current_price': 'Aktueller Preis',
        'buy_button': 'KAUFEN',
        'sell_button': 'VERKAUFEN',
        'trade_amount_placeholder': 'Betrag eingeben ($100-$1000)',
        'deposit_btn': 'Einzahlung',
        'withdraw_btn': 'Abhebung',
        'history_btn': 'Historie',
        'trade_in_progress': 'Trade läuft',
        'entry_price': 'Einstieg',
        'current_price_label': 'Aktuell',
        'profit_label': 'Gewinn',
        'congratulations': 'Glückwunsch! Sie haben gewonnen!',
        'better_luck': 'Viel Glück beim nächsten Mal!',
        'trade_again': 'Erneut Handeln',
        'transaction_history': 'Transaktionshistorie',
        'no_transactions': 'Noch keine Transaktionen',
        'profit': 'Gewinn',
        'return': 'Rendite',
        'new_balance': 'Neues Guthaben'
    },
    
    'fa': {
        'code': 'fa',
        'name': 'فارسی',
        'flag': '🇮🇷',
        'welcome_select_language': '🌍 **به TradeX Pro خوش آمدید!**\n\nلطفاً زبان مورد نظر خود را انتخاب کنید:',
        'welcome_register': '🚀 **به TradeX Pro خوش آمدید، {}!**\n\n🎁 **هدیه ویژه:** 10 دلار رایگان برای شروع معاملات دریافت کنید!\n\nروی "ثبت نام و دریافت 10 دلار" کلیک کنید تا پاداش خود را دریافت کرده و سفر معاملاتی هوش مصنوعی خود را آغاز کنید!',
        'welcome_existing': '🚀 **خوش برگشتید، {}!**\n\nحساب شما آماده معامله است!\n\n💰 **موجودی:** ${:.2f}\n📊 **کل معاملات:** {}\n🏆 **نرخ برد:** {:.1f}%',
        'register_success': '🎉 **ثبت نام موفقیت آمیز!**\n\n💰 **هدیه 10 دلاری اضافه شد!** موجودی اولیه شما اکنون 10,010 دلار است\n\nآماده شروع معاملات هوش مصنوعی هستید؟',
        'trade_button': '🚀 باز کردن TradeX Pro',
        'stats_button': '📊 آمار من',
        'deposit_button': '💰 واریز',
        'withdraw_button': '💸 برداشت',
        'history_button': '📜 تاریخچه',
        'help_button': '❓ راهنما',
        'language_button': '🌍 زبان',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'ربات معاملاتی هوش مصنوعی',
        'balance_label': 'موجودی شما',
        'ai_signal': 'سیگنال هوش مصنوعی',
        'confidence': 'اطمینان',
        'current_price': 'قیمت فعلی',
        'buy_button': 'خرید',
        'sell_button': 'فروش',
        'trade_amount_placeholder': 'مبلغ را وارد کنید ($100-$1000)',
        'deposit_btn': 'واریز',
        'withdraw_btn': 'برداشت',
        'history_btn': 'تاریخچه',
        'trade_in_progress': 'معامله در حال انجام',
        'entry_price': 'ورود',
        'current_price_label': 'فعلی',
        'profit_label': 'سود',
        'congratulations': 'تبریک! شما برنده شدید!',
        'better_luck': 'دفعه بعد شانس بیشتری خواهید داشت!',
        'trade_again': 'معامله مجدد',
        'transaction_history': 'تاریخچه تراکنش‌ها',
        'no_transactions': 'هنوز تراکنشی وجود ندارد',
        'profit': 'سود',
        'return': 'بازده',
        'new_balance': 'موجودی جدید'
    },
    
    'ru': {
        'code': 'ru',
        'name': 'Русский',
        'flag': '🇷🇺',
        'welcome_select_language': '🌍 **Добро пожаловать в TradeX Pro!**\n\nПожалуйста, выберите предпочитаемый язык:',
        'welcome_register': '🚀 **Добро пожаловать в TradeX Pro, {}!**\n\n🎁 **Специальный подарок:** Получите $10 БЕСПЛАТНО для начала торговли!\n\nНажмите "Зарегистрироваться и получить $10", чтобы получить бонус и начать торговлю с ИИ!',
        'welcome_existing': '🚀 **С возвращением, {}!**\n\nВаш аккаунт готов к торговле!\n\n💰 **Баланс:** ${:.2f}\n📊 **Всего сделок:** {}\n🏆 **Процент побед:** {:.1f}%',
        'register_success': '🎉 **Регистрация успешна!**\n\n💰 **Подарок $10 добавлен!** Ваш начальный баланс теперь $10,010\n\nГотовы начать торговлю с ИИ?',
        'trade_button': '🚀 Открыть TradeX Pro',
        'stats_button': '📊 Моя статистика',
        'deposit_button': '💰 Депозит',
        'withdraw_button': '💸 Вывод',
        'history_button': '📜 История',
        'help_button': '❓ Помощь',
        'language_button': '🌍 Язык',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'ИИ-Торговый Бот',
        'balance_label': 'Ваш баланс',
        'ai_signal': 'ИИ Сигнал',
        'confidence': 'Уверенность',
        'current_price': 'Текущая цена',
        'buy_button': 'КУПИТЬ',
        'sell_button': 'ПРОДАТЬ',
        'trade_amount_placeholder': 'Введите сумму ($100-$1000)',
        'deposit_btn': 'Депозит',
        'withdraw_btn': 'Вывод',
        'history_btn': 'История',
        'trade_in_progress': 'Сделка в процессе',
        'entry_price': 'Вход',
        'current_price_label': 'Текущая',
        'profit_label': 'Прибыль',
        'congratulations': 'Поздравляем! Вы выиграли!',
        'better_luck': 'Удачи в следующий раз!',
        'trade_again': 'Торговать снова',
        'transaction_history': 'История транзакций',
        'no_transactions': 'Транзакций пока нет',
        'profit': 'Прибыль',
        'return': 'Доходность',
        'new_balance': 'Новый баланс'
    },
    
    'zh': {
        'code': 'zh',
        'name': '中文',
        'flag': '🇨🇳',
        'welcome_select_language': '🌍 **欢迎使用 TradeX Pro！**\n\n请选择您的首选语言：',
        'welcome_register': '🚀 **欢迎使用 TradeX Pro，{}！**\n\n🎁 **特别礼品：** 免费获得$10开始交易！\n\n点击"注册并获得$10"领取奖金，开始您的AI交易之旅！',
        'welcome_existing': '🚀 **欢迎回来，{}！**\n\n您的账户已准备好交易！\n\n💰 **余额：** ${:.2f}\n📊 **总交易数：** {}\n🏆 **胜率：** {:.1f}%',
        'register_success': '🎉 **注册成功！**\n\n💰 **$10礼品已添加！** 您的初始余额现在是$10,010\n\n准备开始AI交易了吗？',
        'trade_button': '🚀 打开 TradeX Pro',
        'stats_button': '📊 我的统计',
        'deposit_button': '💰 存款',
        'withdraw_button': '💸 提款',
        'history_button': '📜 历史',
        'help_button': '❓ 帮助',
        'language_button': '🌍 语言',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'AI交易机器人',
        'balance_label': '您的余额',
        'ai_signal': 'AI信号',
        'confidence': '置信度',
        'current_price': '当前价格',
        'buy_button': '买入',
        'sell_button': '卖出',
        'trade_amount_placeholder': '输入金额 ($100-$1000)',
        'deposit_btn': '存款',
        'withdraw_btn': '提款',
        'history_btn': '历史',
        'trade_in_progress': '交易进行中',
        'entry_price': '入场',
        'current_price_label': '当前',
        'profit_label': '利润',
        'congratulations': '恭喜！您赢了！',
        'better_luck': '下次好运！',
        'trade_again': '再次交易',
        'transaction_history': '交易历史',
        'no_transactions': '暂无交易',
        'profit': '利润',
        'return': '回报',
        'new_balance': '新余额'
    },
    
    'ja': {
        'code': 'ja',
        'name': '日本語',
        'flag': '🇯🇵',
        'welcome_select_language': '🌍 **TradeX Proへようこそ！**\n\n希望する言語を選択してください：',
        'welcome_register': '🚀 **TradeX Proへようこそ、{}さん！**\n\n🎁 **特別ギフト：** 取引開始のために$10を無料で受け取ってください！\n\n「登録して$10を受け取る」をクリックしてボーナスを受け取り、AI取引の旅を始めましょう！',
        'welcome_existing': '🚀 **おかえりなさい、{}さん！**\n\nあなたのアカウントは取引準備完了です！\n\n💰 **残高：** ${:.2f}\n📊 **総取引数：** {}\n🏆 **勝率：** {:.1f}%',
        'register_success': '🎉 **登録成功！**\n\n💰 **$10ギフトが追加されました！** 初期残高は$10,010になりました\n\nAI取引を始める準備はできましたか？',
        'trade_button': '🚀 TradeX Proを開く',
        'stats_button': '📊 私の統計',
        'deposit_button': '💰 入金',
        'withdraw_button': '💸 出金',
        'history_button': '📜 履歴',
        'help_button': '❓ ヘルプ',
        'language_button': '🌍 言語',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'AI取引ボット',
        'balance_label': 'あなたの残高',
        'ai_signal': 'AIシグナル',
        'confidence': '信頼度',
        'current_price': '現在価格',
        'buy_button': '買い',
        'sell_button': '売り',
        'trade_amount_placeholder': '金額を入力 ($100-$1000)',
        'deposit_btn': '入金',
        'withdraw_btn': '出金',
        'history_btn': '履歴',
        'trade_in_progress': '取引進行中',
        'entry_price': 'エントリー',
        'current_price_label': '現在',
        'profit_label': '利益',
        'congratulations': 'おめでとうございます！勝利しました！',
        'better_luck': '次回頑張ってください！',
        'trade_again': '再度取引',
        'transaction_history': '取引履歴',
        'no_transactions': '取引がまだありません',
        'profit': '利益',
        'return': 'リターン',
        'new_balance': '新しい残高'
    },
    
    'ar': {
        'code': 'ar',
        'name': 'العربية',
        'flag': '🇸🇦',
        'welcome_select_language': '🌍 **مرحباً بك في TradeX Pro!**\n\nيرجى اختيار اللغة المفضلة لديك:',
        'welcome_register': '🚀 **مرحباً بك في TradeX Pro، {}!**\n\n🎁 **هدية خاصة:** احصل على 10$ مجاناً لبدء التداول!\n\nانقر على "سجل واحصل على 10$" لاستلام مكافأتك وبدء رحلة التداول بالذكاء الاصطناعي!',
        'welcome_existing': '🚀 **مرحباً بعودتك، {}!**\n\nحسابك جاهز للتداول!\n\n💰 **الرصيد:** ${:.2f}\n📊 **إجمالي الصفقات:** {}\n🏆 **معدل الفوز:** {:.1f}%',
        'register_success': '🎉 **تم التسجيل بنجاح!**\n\n💰 **تمت إضافة هدية 10$!** رصيدك الأولي أصبح الآن 10,010$\n\nهل أنت مستعد لبدء التداول بالذكاء الاصطناعي؟',
        'trade_button': '🚀 افتح TradeX Pro',
        'stats_button': '📊 إحصائياتي',
        'deposit_button': '💰 إيداع',
        'withdraw_button': '💸 سحب',
        'history_button': '📜 التاريخ',
        'help_button': '❓ مساعدة',
        'language_button': '🌍 اللغة',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'روبوت التداول بالذكاء الاصطناعي',
        'balance_label': 'رصيدك',
        'ai_signal': 'إشارة الذكاء الاصطناعي',
        'confidence': 'الثقة',
        'current_price': 'السعر الحالي',
        'buy_button': 'شراء',
        'sell_button': 'بيع',
        'trade_amount_placeholder': 'أدخل المبلغ ($100-$1000)',
        'deposit_btn': 'إيداع',
        'withdraw_btn': 'سحب',
        'history_btn': 'التاريخ',
        'trade_in_progress': 'الصفقة قيد التنفيذ',
        'entry_price': 'دخول',
        'current_price_label': 'حالي',
        'profit_label': 'ربح',
        'congratulations': 'تهانينا! لقد فزت!',
        'better_luck': 'حظ أفضل في المرة القادمة!',
        'trade_again': 'تداول مرة أخرى',
        'transaction_history': 'تاريخ المعاملات',
        'no_transactions': 'لا توجد معاملات بعد',
        'profit': 'ربح',
        'return': 'عائد',
        'new_balance': 'الرصيد الجديد'
    },
    
    'pt': {
        'code': 'pt',
        'name': 'Português',
        'flag': '🇧🇷',
        'welcome_select_language': '🌍 **Bem-vindo ao TradeX Pro!**\n\nPor favor, selecione seu idioma preferido:',
        'welcome_register': '🚀 **Bem-vindo ao TradeX Pro, {}!**\n\n🎁 **Presente Especial:** Receba $10 GRÁTIS para começar a negociar!\n\nClique em "Registrar e Ganhar $10" para reivindicar seu bônus e começar sua jornada de trading com IA!',
        'welcome_existing': '🚀 **Bem-vindo de volta, {}!**\n\nSua conta está pronta para negociar!\n\n💰 **Saldo:** ${:.2f}\n📊 **Total de Negociações:** {}\n🏆 **Taxa de Vitória:** {:.1f}%',
        'register_success': '🎉 **Registro Bem-sucedido!**\n\n💰 **Presente de $10 Adicionado!** Seu saldo inicial agora é $10,010\n\nPronto para começar o trading com IA?',
        'trade_button': '🚀 Abrir TradeX Pro',
        'stats_button': '📊 Minhas Estatísticas',
        'deposit_button': '💰 Depósito',
        'withdraw_button': '💸 Saque',
        'history_button': '📜 Histórico',
        'help_button': '❓ Ajuda',
        'language_button': '🌍 Idioma',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'Bot de Trading com IA',
        'balance_label': 'Seu Saldo',
        'ai_signal': 'Sinal IA',
        'confidence': 'Confiança',
        'current_price': 'Preço Atual',
        'buy_button': 'COMPRAR',
        'sell_button': 'VENDER',
        'trade_amount_placeholder': 'Digite o valor ($100-$1000)',
        'deposit_btn': 'Depósito',
        'withdraw_btn': 'Saque',
        'history_btn': 'Histórico',
        'trade_in_progress': 'Negociação em Andamento',
        'entry_price': 'Entrada',
        'current_price_label': 'Atual',
        'profit_label': 'Lucro',
        'congratulations': 'Parabéns! Você ganhou!',
        'better_luck': 'Melhor sorte na próxima vez!',
        'trade_again': 'Negociar Novamente',
        'transaction_history': 'Histórico de Transações',
        'no_transactions': 'Nenhuma transação ainda',
        'profit': 'Lucro',
        'return': 'Retorno',
        'new_balance': 'Novo Saldo'
    },
    
    'it': {
        'code': 'it',
        'name': 'Italiano',
        'flag': '🇮🇹',
        'welcome_select_language': '🌍 **Benvenuto in TradeX Pro!**\n\nSi prega di selezionare la lingua preferita:',
        'welcome_register': '🚀 **Benvenuto in TradeX Pro, {}!**\n\n🎁 **Regalo Speciale:** Ricevi $10 GRATIS per iniziare a fare trading!\n\nClicca su "Registrati e Ottieni $10" per riscattare il tuo bonus e iniziare il tuo viaggio di trading IA!',
        'welcome_existing': '🚀 **Bentornato, {}!**\n\nIl tuo account è pronto per il trading!\n\n💰 **Saldo:** ${:.2f}\n📊 **Totale Operazioni:** {}\n🏆 **Tasso di Vittoria:** {:.1f}%',
        'register_success': '🎉 **Registrazione Riuscita!**\n\n💰 **Regalo di $10 Aggiunto!** Il tuo saldo iniziale è ora $10,010\n\nPronto per iniziare il trading IA?',
        'trade_button': '🚀 Apri TradeX Pro',
        'stats_button': '📊 Le Mie Statistiche',
        'deposit_button': '💰 Deposito',
        'withdraw_button': '💸 Prelievo',
        'history_button': '📜 Cronologia',
        'help_button': '❓ Aiuto',
        'language_button': '🌍 Lingua',
        'app_title': 'TradeX Pro',
        'app_subtitle': 'Bot di Trading IA',
        'balance_label': 'Il Tuo Saldo',
        'ai_signal': 'Segnale IA',
        'confidence': 'Confidenza',
        'current_price': 'Prezzo Attuale',
        'buy_button': 'COMPRA',
        'sell_button': 'VENDI',
        'trade_amount_placeholder': 'Inserisci importo ($100-$1000)',
        'deposit_btn': 'Deposito',
        'withdraw_btn': 'Prelievo',
        'history_btn': 'Cronologia',
        'trade_in_progress': 'Operazione in Corso',
        'entry_price': 'Entrata',
        'current_price_label': 'Attuale',
        'profit_label': 'Profitto',
        'congratulations': 'Congratulazioni! Hai vinto!',
        'better_luck': 'Buona fortuna la prossima volta!',
        'trade_again': 'Fai Trading di Nuovo',
        'transaction_history': 'Cronologia Transazioni',
        'no_transactions': 'Nessuna transazione ancora',
        'profit': 'Profitto',
        'return': 'Ritorno',
        'new_balance': 'Nuovo Saldo'
    }
}