name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Run tests
        run: npm test
      - name: Publish (master only)
        if: github.ref == 'refs/heads/master'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          BOT_TOKEN_SECRET: ${{ secrets.BOT_TOKEN_SECRET }}
        run: npx wrangler deploy --var TELEGRAM_BOT_TOKEN:${TELEGRAM_BOT_TOKEN} --var BOT_TOKEN_SECRET:${BOT_TOKEN_SECRET}
